language: ruby
rvm:
- 2.1.4

# Don't install gems that Travis doesn't need.
bundler_args: --without development

# Run specs first, then cucumber features.
script: bundle exec rspec && bundle exec cucumber

deploy:
  provider: heroku
  api_key:
    secure: UEghWfTrAtiEVmiwSUgFrD/Nc+B2lsccIZjj1oJ2O6OAhpG2qgf4+kZKJPgZgkLQyomKpyMWQB8+UjYnwdIgxs7sospf/+eqxyOK7XTUv1sy7aVKun/8jU2F5CAUA+eRQLGW/0WoJ+s6yZf6QP3RUGG4uO4iuw0o0Re1KxGjAT0=
  app: celebrity-game
  on:
    repo: winnab/celebrity
